GraduationDku/tastyHub

- fe/package-lock.json
- fe/package.json
- fe/src/components/Login.js
- fe/src/components/Signup.js
- fe/src/components/Village.js
- fe/yarn.lock
- 이슈 번호: #4
로그인, 회원가입 및 지도 API 
회원가입 시 정규표현식
네이버 지도 API
> User village

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/repository/UserRepository.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserServiceImpl.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtUtil.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/UserDetailsServiceImpl.java
- be/tastyhub/src/main/resources/application.yml
로그인 로직 API 검증 및 jwt 오류 해결
1. prefix 추가
2. secret Key 생성 로직 변경
3. redis host이름 변경
resolve : #14
- 이슈 번호: #14 
로그인 로직 API 검증 및 jwt 오류 해결
1. prefix 추가
2. secret Key 생성 로직 변경
3. redis host이름 변경
Close: #14
> fix <(user, env)> : 로그인 로직 진행시 jwt 오류 해결

- be/tastyhub/src/main/java/com/example/tastyhub/common/config/SecurityConfig.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/village/controller/VillageController.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtAuthFilter.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/JwtUtil.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/UserDetailsImpl.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/UserDetailsServiceImpl.java
resolve : #16
- 이슈 번호: #16 
JWT 토큰 요구 요청 시 발생 오류 해결
> fix <(env)> : jwt가 요구되는 요청 시 오류 해결

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/dtos/UserDto.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/repository/UserRepository.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/repository/UserRepositoryQuery.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/repository/UserRepositoryQueryImpl.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserServiceImpl.java
- be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/service/UserServiceImplTest.java
- be/tastyhub/src/test/java/com/example/tastyhub/common/domain/village/service/VillageServiceImplTest.java
사용자 검색 로직 쿼리DSL 활용을 통해 기능 향상
다만 아직 단위테스트 작성 X, 후에 단위테스트만 작성할 예정
#19
- 이슈 번호: #19 
사용자 검색 로직 쿼리DSL을 사용해서 최적화
기존의 경우 해당 nickname인 경우만 조회가 되었지만 현재는 해당 닉네임이 글자가 포함된 닉네임이면 조회되도록 변경
> feat <(user)> : 사용자 검색 로직 작성

- fe/src/components/Login.js
- fe/src/components/Navbar.js
> fix <(user)>: 경로명 수정

- .github/workflows/DockerCD.yml
- be/tastyhub/Dockerfile
> Skyriv213 patch 2

- .github/workflows/DockerCD.yml
- be/tastyhub/Dockerfile
- compose.yaml
- 이슈 번호: #47 
개발자 통합 개발환경 세팅  - application.yml 및 secret 설정
> Dockerwork

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/controller/UserController.java
#62
- 이슈 번호: #62
HTTP Method 방식 변경
> feature <(user)> : 로그인 HTTP Method 방식 변경

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/post/repository/PostRepositoryQueryImpl.java
동네정보 비교 -> 동네정보.이름 비교로 변경
#70
- 이슈 번호: #70
동네정보 이름 비교로 로직 수정
> Fix <(post)> : 게시글 조회 로직 조건 변경

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/naver/service/NaverService.java
네이버 컨테이너에서 UnAuthorization 문제 발생
해결을 위해 키,값 이 들어갔는지 확인
#76
- 이슈 번호: #76 
Id, secret 조회
> fix <(Naver)> : Unauthorization docker container

- fe/src/App.js
- fe/src/components/CreateRecipe.js
- fe/src/components/CreateRecipeReview.js
- fe/src/components/Like.js
- fe/src/components/MainMypage.js
- fe/src/components/Navbar.js
- fe/src/components/Post.js
- fe/src/components/Recipedetails.js
- fe/src/components/Scrap.js
- fe/src/components/SendChat.js
> feat <(review)> : 레시피 리뷰

- fe/src/App.js
- fe/src/components/Comment.js
- fe/src/components/Post.js
- fe/src/components/PostDetails.js
> feat <(post)> : 게시물 상세조회 기능

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/foodInformation/entity/FoodInformation.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/entity/Recipe.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/recipe/service/RecipeServiceImpl.java
recipe foodInformation 누락된 로직 발견 및 수정
#85
- 이슈 번호: #85 
recipe foodInformation 누락된 로직 발견 및 긴급 수정
recipe 생성 시 recipe과 foodInformation의 객체 연관관계 설정 후 repository 저장
> fix <(recipe)>  : recipe, foodInformation 연관관계 누락 수정

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/user/service/UserServiceImpl.java
> fix <(user)> : user 생성시 이미지 입력 없으면 기본 프로필 이미지로 설정

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/controller/ChatRoomController.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomServiceImpl.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/userChat/repository/UserChatRoomRepository.java
#100
- 이슈 번호: #100
chatting 기능 구현을 위해 로직 수정
**chatting 기능 구현을 위해 로직 수정**
> fix <(chatting)> : chatting 기능 구현을 위해 로직 수정

- README.md
> Sep037 patch 1

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/controller/ChatRoomController.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/repository/ChatRoomRepository.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomService.java
- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/service/ChatRoomServiceImpl.java
roomId 조회가 아닌 PostId를 통해 조회 진행
#100
- 이슈 번호: #100 
채팅방 로직 수정
채팅방 생성 검증 로직 수정
roomId -> postId로 검증 변수 변환
> fix <(chat)> : 채팅방 상태 확인 로직 변경

- fe/src/components/MainChat.js
- fe/src/components/MypageEdit.js
- fe/src/components/Post.js
- fe/src/components/SendChat.js
> fix <(bug)> : 오류 수정

- be/tastyhub/src/main/java/com/example/tastyhub/common/domain/chat/controller/ChatRoomController.java
> fix <(chat)> : roomId 수정

- be/tastyhub/src/main/java/com/example/tastyhub/common/config/SecurityConfig.java
> fix <(cors)> : cors 허용 재설정

- fe/src/components/Post/Post.js
- fe/src/index.js
> Refactory <(Bug)> : 2번씩 렌더링 되는 오류 해결

- fe/src/App.js
- fe/src/components/Chat/MainChat.js
- fe/src/components/Navbar.js
- fe/src/components/Recipe/Recipe.js
- fe/src/index.js
> Refactory <(pagination)> : 페이지네이션 마무리 작업 및 사용자 검색 오류 수정

- be/tastyhub/src/test/java/com/example/tastyhub/common/domain/comment/controller/CommentControllerTest.java
- be/tastyhub/src/test/java/com/example/tastyhub/common/domain/post/controller/PostControllerTest.java
- be/tastyhub/src/test/java/com/example/tastyhub/common/domain/user/controller/UserControllerTest.java
> Test <(Total)> : 오류 테스트 코드 주석처리

- be/tastyhub/src/main/java/com/example/tastyhub/common/utils/Jwt/AccessTokenService.java
#145
- 이슈 번호: #145
리프레시 토큰 테스트 후 엑세스 토큰 만료시간 롤백
> feature <(accessToken)> : 엑세스 토큰 만료 시간 롤백

- fe/package-lock.json
- fe/package.json
- fe/src/components/Recipe/CreateRecipe.js
- fe/src/components/Recipe/Recipedetails.js
> Video front

- be/tastyhub/src/test/java/com/example/tastyhub/common/domain/recipe/controller/RecipeControllerTest.java
이미지 생성을 위한 테스트 코드 주석 처리
#177
- 이슈 번호: #177 
빠른 기능 구현을 위한 테스트 코드 주석처리
> fix <(image)> : 이미지 생성을 위한 테스트 코드 주석 처리 진행
